Further clarifications about credential validity without status assertions
peppelinux/draft-demarco-oauth-status-assertions pull request #78
Opened 2024-06-25 12:44 UTC by peppelinux

As discussed this PR offers more details about what we intend to be valid/invalid following the evidence brought or not borught using hte status assertions

2024-06-28 07:56 UTC, SaraConsoliACN approved these changes

2024-06-28 13:32 UTC, fmarino-ipzs approved these changes

2024-06-29 09:39 UTC, OR13 requested changes
When we said SHOULD, we need to explain when it can be ignored, and when it becomes MUST.

2024-06-29 09:39 UTC, OR13 commented on draft-demarco-oauth-status-assertions.md
> +The expiration datetime MUST be
```suggestion
and the Digital Credential referred to SHOULD NOT
be considered as having a valid status, unless there exists some specific verifier policy that provides stronger guidance.
The expiration datetime MUST be
```

2024-06-30 13:03 UTC, OR13 approved these changes

2024-07-01 14:16 UTC, merged